---
# tasks file for MicroJoe.gitea

- name: Ensure group exists
  user:
    name: "{{ gitea_group }}"

- name: Ensure user exists
  user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"

- name: Download gitea source tree
  become: yes
  become_user: "{{ gitea_user }}"
  get_url:
    url: "https://github.com/go-gitea/gitea/archive/v{{ gitea_version }}.tar.gz"
    dest: "{{ gitea_home }}/gitea-{{ gitea_version }}.tar.gz"

- name: Create directory for archive extraction
  become: yes
  become_user: "{{ gitea_user }}"
  file:
    path: "{{ gitea_base }}"
    state: directory

- name: Extract gitea
  become: yes
  become_user: "{{ gitea_user }}"
  unarchive:
    remote_src: yes
    src: "{{ gitea_home }}/gitea-{{ gitea_version }}.tar.gz"
    dest: "{{ gitea_base }}"
    extra_opts: ["--strip-components=1"]

- name: Download gitea binary
  become: yes
  become_user: "{{ gitea_user }}"
  get_url:
    url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
    dest: "{{ gitea_base }}/gitea"
    mode: 0755

# PostgreSQL commands

- name: Create postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ gitea_db_user }}"
    password: "{{ gitea_db_password }}"

- name: Create postgresql database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ gitea_db_name }}"
    owner: "{{ gitea_db_user }}"
    encoding: UTF-8
    template: template0

# Systemd service

- name: Install systemd update service
  template:
    src: templates/gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    mode: 0664

- name: Enable systemd update service
  systemd:
    name: gitea
    state: started
    enabled: yes
    daemon_reload: yes
