---
# tasks file for MicroJoe.gogs

- name: Ensure group exists
  user:
    name: "{{ gogs_group }}"

- name: Ensure user exists
  user:
    name: "{{ gogs_user }}"
    group: "{{ gogs_group }}"

- name: Download gogs
  become: yes
  become_user: "{{ gogs_user }}"
  get_url:
    url: "https://cdn.gogs.io/{{ gogs_version }}/linux_amd64.tar.gz"
    dest: "{{ gogs_home }}/gogs-{{ gogs_version }}.tar.gz"
    checksum: sha256:ae6c81a7e00a5bc96f9f165c234f8ea156f4ef4735a55ba279187786157ddf1a

- name: Create directory for archive extraction
  become: yes
  become_user: "{{ gogs_user }}"
  file:
    path: "{{ gogs_base }}"
    state: directory

- name: Extract gogs
  become: yes
  become_user: "{{ gogs_user }}"
  unarchive:
    remote_src: yes
    src: "{{ gogs_home }}/gogs-{{ gogs_version }}.tar.gz"
    dest: "{{ gogs_base }}"
    extra_opts: ["--strip-components=1"]

# PostgreSQL commands

- name: Create postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ gogs_db_user }}"
    password: "{{ gogs_db_password }}"

- name: Create postgresql database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ gogs_db_name }}"
    owner: "{{ gogs_db_user }}"
    encoding: UTF-8
    template: template0

# Systemd service

- name: Install systemd update service
  copy:
    remote_src: yes
    src: "{{ gogs_base }}/scripts/systemd/gogs.service"
    dest: /etc/systemd/system/gogs.service
    mode: 0664

- name: Enable systemd update service
  systemd:
    name: gogs
    state: started
    enabled: yes
    daemon_reload: yes
